version: 2.1

# These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:
    run-integration-tests:
        description: An internal flag to prevent integration test from running before a development version has been created.
        type: boolean
        default: false
    dev-orb-version:
        description: >
            The development version of the orb to test.
            This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
            A "dev:alpha" version must exist for the initial pipeline run.
        type: string
        default: "dev:alpha"

orbs:
    orb-tools: circleci/orb-tools@10.0
    composer: stockfiller/composer@<<pipeline.parameters.dev-orb-version>>

jobs:
    integration-tests-for-your-orb:
        executor: orb-tools/ubuntu
        steps:
            - checkout
            - composer/install_bin
            - composer/install:
                  working-dir: tests
workflows:
    integration-test_deploy:
        jobs:
            - integration-tests-for-your-orb
            -   orb-tools/dev-promote-prod-from-commit-subject:
                    add-pr-comment: false
                    fail-if-semver-not-indicated: false
                    filters:
                        branches:
                            only: master
                    orb-name: stockfiller/composer
                    publish-version-tag: false
                    requires:
                        - integration-tests-for-your-orb
        when: << pipeline.parameters.run-integration-tests >>
    test-pack:
        jobs:
            - orb-tools/lint
            - orb-tools/pack
            -   orb-tools/publish-dev:
                    orb-name: stockfiller/composer
                    requires:
                        - orb-tools/lint
                        - orb-tools/pack
            -   orb-tools/trigger-integration-tests-workflow:
                    name: trigger-integration-dev
                    requires:
                        - orb-tools/publish-dev
        unless: << pipeline.parameters.run-integration-tests >>
